#spring:
#  output:
#    ansi:
#      enabled: always
#
#  datasource:
#    url: jdbc:oracle:thin:@capstone2_high?TNS_ADMIN=/Users/admin/Desktop/capstone2/Wallet_Capstone2
#    username: admin
#    password: Odunkshot0606*
#    driver-class-name: oracle.jdbc.OracleDriver
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#        default_batch_fetch_size: 100
#
#logging.level:
#  org.hibernate.SQL: debug
#  #org.hibernate.type: trace
#server:
#  port: 9090

###=========
#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/capstone2
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
###==========

#server:
#  port: 9090
spring:
  datasource:
    #url: jdbc:mariadb://${TODO_MYSQL_HOST}:${TODO_MYSQL_PORT}/${TODO_DATA_BASE_NAME}?useSSL=false
    #username: ${TODO_MYSQL_USER_NAME}
    #password: ${TODO_MYSQL_PASSWORD}
    url: jdbc:mariadb://localhost:3306/capstone2
    driver-class-name: org.mariadb.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update   #create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace

cloud:
  aws:
    s3:
      bucket: yw-capstone2-bucket
    credentials:
      #access-key: ${ACCESS_KEY}
      #secret-key: ${SECRET_KEY}
      access-key: AKIAVRYLLLXH4G56KVWD
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false